wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1678475097.956084
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.7.4
      5: 0.13.11
      8:
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
